actor_dropout: null
actor_lr: 0.0003
batch_size: 256
beta: 3.0
buffer_size: 2000000
checkpoints_path: unitree_a1_saved_models/IQL-UnitreeA1_simple_perfect-9ac7d949
device: cuda
discount: 0.99
env: UnitreeA1_simple_perfect
eval_freq: 5000
group: IQL-D4RL
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: IQL-UnitreeA1_simple_perfect-9ac7d949
normalize: true
normalize_reward: false
project: CORL
qf_lr: 0.0003
seed: 0
tau: 0.005
vf_lr: 0.0003
